---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.maestro.rbac.serviceAccountName }}
---
{{- if .Values.maestro.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.maestro.rbac.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.maestro.rbac.serviceAccountName }}
  namespace: orb-live
roleRef:
  kind: ClusterRole
  name: {{ .Values.maestro.rbac.ClusterRole }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
