---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-maestro-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-maestro-role
subjects:
- kind: ServiceAccount
  name: k8s-maestro-role
  namespace: orb-live
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
