apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orb-tls
  namespace: orb
spec:
  dnsNames:
    - orb.example.com
  secretName: orb-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
