{{- $authPwd := default (include "nats.randomPassword" .) .Values.auth.password -}}
{{- $clusterAuthPwd := default (include "nats.randomPassword" .) .Values.clusterAuth.password -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{ .Values.natsFilename }}.conf: |-
    listen: 0.0.0.0:{{ .Values.client.service.port }}
    http: 0.0.0.0:{{ .Values.monitoring.service.port }}

    # Authorization for client connections
    {{- if .Values.auth.enabled }}
    authorization {
      {{- if .Values.auth.user }}
      user: {{ .Values.auth.user | quote }}
      password: {{ $authPwd | quote }}
      {{- else if .Values.auth.token }}
      token: {{ .Values.auth.token | quote }}
      {{- end }}
      timeout:  {{ int .Values.auth.timeout }}
    }
    {{- end }}

    # Logging options
    debug: {{ ternary "true" "false" (or .Values.debug.enabled .Values.diagnosticMode.enabled) }}
    trace: {{ ternary "true" "false" (or .Values.debug.trace .Values.diagnosticMode.enabled) }}
    logtime: {{ ternary "true" "false" (or .Values.debug.logtime .Values.diagnosticMode.enabled) }}

    # Pid file
    pid_file: "/tmp/{{ .Values.natsFilename }}.pid"

    # Some system overrides
    {{- if .Values.maxConnections }}
    max_connections: {{ int .Values.maxConnections }}
    {{- end }}
    {{- if .Values.maxControlLine }}
    max_control_line: {{ int .Values.maxControlLine }}
    {{- end }}
    {{- if .Values.maxPayload }}
    max_payload: {{ int .Values.maxPayload }}
    {{- end }}
    {{- if .Values.writeDeadline }}
    write_deadline: {{ .Values.writeDeadline | quote }}
    {{- end }}


    # Clustering definition
    cluster {
      listen: 0.0.0.0:{{ .Values.cluster.service.port }}
      name: orb_nats
      # Authorization for cluster connections
      {{- if .Values.clusterAuth.enabled }}
      authorization {
        {{- if .Values.clusterAuth.user }}
        user: {{ .Values.clusterAuth.user | quote }}
        password: {{ $clusterAuthPwd | quote }}
        {{- else if .Values.clusterAuth.token }}
        token: {{ .Values.clusterAuth.token | quote }}
        {{- end }}
        timeout:  1
      }
      {{- end }}

      # Routes are actively solicited and connected to from this server.
      # Other servers can connect to us if they supply the correct credentials
      # in their routes definitions from above
      routes = [
        {{- if .Values.clusterAuth.enabled }}
        {{- if .Values.clusterAuth.user }}
        nats://{{ .Values.clusterAuth.user }}:{{ $clusterAuthPwd }}@{{ template "common.names.fullname" . }}-cluster:{{ .Values.cluster.service.port }}
        {{- else if .Values.clusterAuth.token }}
        nats://{{ .Values.clusterAuth.token }}@{{ template "common.names.fullname" . }}-cluster:{{ .Values.cluster.service.port }}
        {{- end }}
        {{- else }}
        nats://{{ template "common.names.fullname" . }}-cluster:{{ .Values.cluster.service.port }}
        {{- end }}
      ]

      {{- if .Values.cluster.connectRetries }}
      # Configure number of connect retries for implicit routes
      connect_retries: {{ .Values.cluster.connectRetries }}
      {{- end }}
    }
