{{- if .Values.migrate.autoMigrate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-migrate
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
{{- end }}