# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-policies
spec:
  selector:
    app: {{ .Release.Name }}
    component: policies
  ports:
    - protocol: TCP
      port: {{ .Values.policies.httpPort }}
      name: {{ .Release.Name }}-policies-http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-policies-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: policies
  ports:
    - port: {{ .Values.policies.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-policies-{{ .Values.policies.httpPort }}
    - port: {{ .Values.policies.grpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-policies-{{ .Values.policies.grpcPort }}
  clusterIP: None
