---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-sinker
spec:
  selector:
    app: {{ .Release.Name }}
    component: otel-sinker
  ports:
    - protocol: TCP
      port: {{ .Values.sinkerOtel.httpPort }}
      name: {{ .Release.Name }}-otel-sinker-http
