# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sinks
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: sinks
  template:
    metadata:
      annotations:
        commit_sha: {{ .Values.defaults.image.commitHash }}
      {{- with .Values.sinks.metadata.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
        component: sinks
    spec:
      containers:
        - env:
            - name: MF_JAEGER_URL
            {{ if not .Values.defaults.jaegerHost }}
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            {{ else }}
              value: {{ .Values.defaults.jaegerHost }}:{{ .Values.defaults.jaegerPort }}
            {{ end }}
            - name: ORB_SINKS_DB
              value: {{ index .Values "postgresql" "postgresqlDatabase" }}
            - name: ORB_SINKS_DB_HOST
            {{ if not .Values.sinks.dbHost }}
              value: {{ .Release.Name }}-postgresql
            {{ else }}
              value: {{ .Values.sinks.dbHost }}
            {{ end }}
            - name: ORB_SINKS_DB_PASS
            {{ if not .Values.sinks.secretPass }}
              value: {{ index .Values "postgresql" "postgresqlPassword" }}
            {{ else }}
              valueFrom :
                secretKeyRef :
                  name : orb-sinks-credentials
                  key : password
                  optional : false
            {{ end }}
            - name: ORB_SINKS_DB_PORT
              value: "{{ .Values.sinks.dbPort }}"
            - name: ORB_SINKS_DB_SSL_MODE
              value: "{{ .Values.sinks.dbSSL }}"
            - name: ORB_SINKS_DB_USER
            {{ if not .Values.sinks.secretPass }}
              value: {{ index .Values "postgresql" "postgresqlUsername" }}
            {{ else }}
              valueFrom :
                secretKeyRef :
                  name : orb-sinks-credentials
                  key : username
                  optional : false
            {{ end }}
            - name: ORB_SINKS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: orb-sinks-encryption-key
                  key: key
                  optional: false
            - name: ORB_SINKS_GRPC_PORT
              value: "{{ .Values.sinks.grpcPort }}"
            - name: ORB_SINKS_ES_URL
            {{ if not .Values.sinks.redisHost }}
              value: {{ .Release.Name }}-redis-master:{{ .Values.sinks.redisPort }}
            {{ else }}
              value: {{ .Values.sinks.redisHost }}:{{ .Values.sinks.redisPort }}
            {{ end }}
            - name: ORB_SINKS_HTTP_PORT
              value: "{{ .Values.sinks.httpPort }}"
            - name: ORB_SINKS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.sinks.logLevel }}
            - name: MF_AUTH_GRPC_URL
              value:
                {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
          image: "{{ default .Values.defaults.image.repository .Values.sinks.image.repository }}/{{ default .Values.sinks.image.name }}:{{ default .Values.defaults.image.tag .Values.sinks.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.sinks.image.pullPolicy }}
          name: {{ .Release.Name }}-sinks
          ports:
            - containerPort: {{ .Values.sinks.httpPort }}
              protocol: TCP
            - containerPort: 2345
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
