name: Chart Version Check

on:
  pull_request:

jobs:
  check-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: check chart release
        shell: bash
        run: |
          file="charts/orb/Chart.yaml"
          while IFS= read -r line
          do
            if [[ $line =~ (^version: ([A-Za-z0-9]+(\.[A-Za-z0-9]+)+)$) ]]; then              
              # check if latest release tag is same version

              echo "ERROR - version already released: '${BASH_REMATCH[2]}'"
              echo "Please choose a version number that never was launched"
              exit 1
            fi
          done <"$file"
