name: Chart Version Check

on:
  pull_request:

jobs:
  chart-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:       
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'

      - name: install chart release
        run: |
          cd charts/orb/
          str=$(<Chart.yaml)
          if [[ $str =~ (^version: ([A-Za-z0-9]+(\.[A-Za-z0-9]+)+)$) ]]; then
            echo "match: '${BASH_REMATCH[2]}'"
          else
            echo "no match found"
          fi
