name: Chart Version Check

on:
  pull_request:

jobs:
  check-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: check chart release
        shell: bash
        run: |
          input="charts/orb/Chart.yaml"
          while IFS= read -r -uN line
          do
            if [[ $line =~ (^\s+version: ([A-Za-z0-9]+(\.[A-Za-z0-9]+)+)$) ]]; then
              echo "match: '${BASH_REMATCH[2]}'"
            fi
            echo "$line"
          done N< $input

