name: Docker build

on:
  push:
    branches:
      - main

jobs:
  chart-release:
    name: Chart Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:       
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'

      - name: install CR
        run: |
          git clone https://github.com/helm/chart-releaser.git
          cd chart-releaser/
          go build -o cr ./cr/main.go
          mv cr /usr/local/bin/
          chmod a+x /usr/local/bin/cr
          cd ..
          rm -rf chart-releaser

      - name: checkout code
        uses: actions/checkout@v3

      - name: debug files
        run: |
          ls -lha        

      - name: create deploy folder
        run: |
          mkdir .deploy

      - name: create chart package
        run: |
          make package

      - name: upload chart package
        run: |
          make ghtoken=${ secrets.GITHUB_TOKEN } upload

      - name: indexing chart package
        run: |
          make index
