name: Chart Release

on:
  push:
    branches:
      - main
      - etaques-patch-1

jobs:
  chart-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:       
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'

      - name: install CR and helm
        run: |
          git clone https://github.com/helm/chart-releaser.git
          cd chart-releaser/
          go build -o cr ./cr/main.go
          mv cr /usr/local/bin/
          chmod a+x /usr/local/bin/cr
          cd ..
          rm -rf chart-releaser

      - name: install helm
        run: |
          cd /tmp
	  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
   
      - name: checkout code
        uses: actions/checkout@v3

      - name: debug files
        run: |
          ls -lha        

      - name: create deploy folder
        run: |
          mkdir .deploy

      - name: install helm dependencies
        run: |
          make prepare-helm

      - name: create chart package
        run: |
          make branch=${{ github.ref_name }} package

      - name: upload chart package
        run: |
          make branch=${{ github.ref_name }} ghtoken=${ secrets.GITHUB_TOKEN } upload

      - name: indexing chart package
        run: |
          make branch=${{ github.ref_name }} ghtoken=${ secrets.GITHUB_TOKEN } index
