name: Chart Release

on:
  push:
    branches:
      - main

jobs:
  chart-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:       
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'

      - name: install chart release
        run: |
          git clone https://github.com/helm/chart-releaser.git
          cd chart-releaser/
          go build -o cr-bin ./cr/main.go
          sudo mv cr-bin /usr/local/bin/cr
          sudo chmod a+rx /usr/local/bin/cr
          sudo chown root.root /usr/local/bin/cr
          cd ..
          rm -rf chart-releaser
          cr version

      - name: install helm
        run: cd /tmp && curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: checkout code
        uses: actions/checkout@v3        

      - name: install helm dependencies
        run: |
          make prepare-helm

      - name: create deploy folder
        run: |
          mkdir .deploy

      - name: create chart package
        run: |
          make branch=${{ github.ref_name }} package

      - name: upload chart package
        run: |
          make branch=${{ github.ref_name }} ghtoken=${{ secrets.GITHUB_TOKEN }} upload

      - name: indexing chart package
        run: |
          make branch=${{ github.ref_name }} ghtoken=${{ secrets.GITHUB_TOKEN }} index
